"""step5_add_estimation_and_streaks

Revision ID: 1a99071ec593
Revises: 7ad1e6bb16eb
Create Date: 2026-06-30 23:19:07.805340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a99071ec593'
down_revision: Union[str, None] = '7ad1e6bb16eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estimation_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.Enum('assignment', 'project', 'bill', 'application', 'personal_goal', 'other', name='tasktype'), nullable=False),
    sa.Column('adjustment_factor', sa.Float(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estimation_profiles_id'), 'estimation_profiles', ['id'], unique=False)
    op.add_column('users', sa.Column('current_streak_days', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('last_active_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_active_date')
    op.drop_column('users', 'current_streak_days')
    op.drop_index(op.f('ix_estimation_profiles_id'), table_name='estimation_profiles')
    op.drop_table('estimation_profiles')
    # ### end Alembic commands ###
