"""add_completed_at_and_actual_hours_to_task_steps

Revision ID: d97a833837a7
Revises: d1534440a0c3
Create Date: 2026-06-30 22:11:45.221716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd97a833837a7'
down_revision: Union[str, None] = 'd1534440a0c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_steps', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('task_steps', sa.Column('actual_hours_spent', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_steps', 'actual_hours_spent')
    op.drop_column('task_steps', 'completed_at')
    # ### end Alembic commands ###
